name: pp_exec_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - arrow-cpp=7.0.0=py39h74dfcfe_7_cpu
  - aws-c-cal=0.5.11=h95a6274_0
  - aws-c-common=0.6.2=h7f98852_0
  - aws-c-event-stream=0.2.7=h3541f99_13
  - aws-c-io=0.10.5=hfb6a706_0
  - aws-checksums=0.1.11=ha31a3da_7
  - aws-sdk-cpp=1.8.186=hb4091e7_3
  - blas=1.0=openblas
  - bottle=0.12.18=py_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.01.10=h06a4308_0
  - fastparquet=0.5.0=py39hce1f21e_1
  - fftw=3.3.9=h27cfd23_1
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.6.0=h6f12383_0
  - grpc-cpp=1.45.2=hd8f4eba_3
  - gunicorn=20.1.0=py39hf3d152e_2
  - joblib=1.1.1=py39h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=14_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=14_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=7.83.1=h7bff187_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - libgoogle-cloud=1.40.2=habd0e3a_0
  - liblapack=3.9.0=14_linux64_openblas
  - libllvm10=10.0.1=hbcb73fb_5
  - libnghttp2=1.47.0=h727a467_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libprotobuf=3.20.1=h6239696_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libthrift=0.16.0=h519c5ea_1
  - libutf8proc=2.7.0=h7f98852_0
  - libxgboost=1.5.0=h6a678d5_2
  - libzlib=1.2.11=h166bdaf_1014
  - llvmlite=0.36.0=py39h612dafd_4
  - lz4-c=1.9.3=h9c3ff4c_1
  - ncurses=6.3=h27087fc_1
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.53.1=py39ha9443f7_0
  - numexpr=2.8.0=py39h194a79d_102
  - numpy=1.22.4=py39hc58783e_0
  - openblas=0.3.20=pthreads_h320a7e8_0
  - openssl=1.1.1t=h7f8727e_0
  - orc=1.7.3=h6c59b99_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py39h1832856_2
  - parquet-cpp=1.5.1=2
  - patsy=0.5.2=py39h06a4308_1
  - pip=22.1.1=pyhd8ed1ab_0
  - py-xgboost=1.5.0=py39h06a4308_2
  - pyarrow=7.0.0=py39h42d110c_7_cpu
  - pyparsing=3.0.9=py39h06a4308_0
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=pyhd8ed1ab_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.1=h46c0cb4_0
  - s2n=1.0.10=h9b69904_0
  - scikit-learn=1.1.3=py39h6a678d5_0
  - scipy=1.9.3
  - setuptools=62.3.2=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.38.5=h4ff8645_0
  - statsmodels=0.13.2=py39h7f8727e_0
  - tbb=2020.3=hfd86e86_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - thrift=0.11.0=py39h295c915_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2022a=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xgboost=1.5.0=py39h06a4308_2
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - --extra-index-url http://s.dev.isgneuro.com/repository/ot.platform/simple
    - --trusted-host s.dev.isgneuro.com
    - cmdstanpy==1.0.8
    - contourpy==1.0.6
    - convertdate==2.4.0
    - cycler==0.11.0
    - ephem==4.1.3
    - execution-environment==1.2.3
    - fonttools==4.38.0
    - hijri-converter==2.2.4
    - holidays==0.17
    - kiwisolver==1.4.4
    - korean-lunar-calendar==0.3.1
    - lunarcalendar==0.0.9
    - matplotlib==3.6.2
    - otlang==1.2.0
    - pillow==9.3.0
    - prophet==1.1.1
    - pymeeus==0.5.11
    - setuptools-git==1.2
    - tatsu==5.6.1
    - tqdm==4.64.1